services:
  db:
    image: postgres:16.3
    container_name: postgres-db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - backend 
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORTS}
  
volumes:
  db-data:

networks:
  backend: